/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { MyGroups as MyGroups } from './components/my-groups/my-groups';

interface HTMLMyGroupsElement extends MyGroups, HTMLElement {
}
declare var HTMLMyGroupsElement: {
  prototype: HTMLMyGroupsElement;
  new (): HTMLMyGroupsElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-groups": HTMLMyGroupsElement;
  }
  interface ElementTagNameMap {
      "my-groups": HTMLMyGroupsElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-groups": JSXElements.MyGroupsAttributes;
      }
  }
  namespace JSXElements {
      export interface MyGroupsAttributes extends HTMLAttributes {
        
          setGroupHandler?: any,
          groupResetHandler?: any,
          getStudentsFromServer?: any,
          renderGroups?: any,
          apiRootUrl?: any
      }
  }
}

import { MyMain as MyMain } from './components/my-main/my-main';

interface HTMLMyMainElement extends MyMain, HTMLElement {
}
declare var HTMLMyMainElement: {
  prototype: HTMLMyMainElement;
  new (): HTMLMyMainElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-main": HTMLMyMainElement;
  }
  interface ElementTagNameMap {
      "my-main": HTMLMyMainElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-main": JSXElements.MyMainAttributes;
      }
  }
  namespace JSXElements {
      export interface MyMainAttributes extends HTMLAttributes {
        
      }
  }
}

import { MyStar as MyStar } from './components/my-star/my-star';

interface HTMLMyStarElement extends MyStar, HTMLElement {
}
declare var HTMLMyStarElement: {
  prototype: HTMLMyStarElement;
  new (): HTMLMyStarElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-star": HTMLMyStarElement;
  }
  interface ElementTagNameMap {
      "my-star": HTMLMyStarElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-star": JSXElements.MyStarAttributes;
      }
  }
  namespace JSXElements {
      export interface MyStarAttributes extends HTMLAttributes {
        
          randomColor?: any
      }
  }
}

import { MyStudentList as MyStudentList } from './components/my-student-list/my-student-list';

interface HTMLMyStudentListElement extends MyStudentList, HTMLElement {
}
declare var HTMLMyStudentListElement: {
  prototype: HTMLMyStudentListElement;
  new (): HTMLMyStudentListElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-student-list": HTMLMyStudentListElement;
  }
  interface ElementTagNameMap {
      "my-student-list": HTMLMyStudentListElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-student-list": JSXElements.MyStudentListAttributes;
      }
  }
  namespace JSXElements {
      export interface MyStudentListAttributes extends HTMLAttributes {
        
          studentGroup?: any,
          yoy?: any,
          furt?: any
      }
  }
}

import { MyStudentRow as MyStudentRow } from './components/my-student-row/my-student-row';

interface HTMLMyStudentRowElement extends MyStudentRow, HTMLElement {
}
declare var HTMLMyStudentRowElement: {
  prototype: HTMLMyStudentRowElement;
  new (): HTMLMyStudentRowElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-student-row": HTMLMyStudentRowElement;
  }
  interface ElementTagNameMap {
      "my-student-row": HTMLMyStudentRowElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-student-row": JSXElements.MyStudentRowAttributes;
      }
  }
  namespace JSXElements {
      export interface MyStudentRowAttributes extends HTMLAttributes {
        
          addStarHandler?: any,
          buildScoresArray?: any,
          removeStarHandler?: any,
          student?: any,
          yoy?: any,
          furt?: any
      }
  }
}

